[workspace]
members = [
	"typify",
	"typify-impl",
	"typify-macro",
	"typify-test",
	"cargo-typify",
	"example-build",
	"example-macro",
]

[workspace.dependencies]
schemars = "0.8.11"

#[patch.crates-io]
#serde_tokenstream = { path = "../serde_tokenstream" }

