[package]
name = "cargo-typify"
version = "0.0.11-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
typify = { version = "0.0.11-dev", path = "../typify" }
color-eyre = "0.6"
serde_json = "1.0.93"
schemars = "0.8.11"
